development: 
  cloud_name: "hkbjwypvm"
  api_key: "881343788991167"
  api_secret: "tLuZKFPtCzJxrBp31M1G258pAa0"
  secure: true

production:
  cloud_name: "hkbjwypvm"
  api_key: "881343788991167"
  api_secret: "tLuZKFPtCzJxrBp31M1G258pAa0"
  secure:true